// <auto-generated />
using System;
using Cinema.Areas.Admin.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Cinema.Migrations
{
    [DbContext(typeof(DPContext))]
    partial class DPContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Cinema.Areas.Admin.Models.AdminModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("TaiKhoan")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("tb_Admin");
                });

            modelBuilder.Entity("Cinema.Areas.Admin.Models.CumRapModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("TenCum")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("tb_CumRap");
                });

            modelBuilder.Entity("Cinema.Areas.Admin.Models.GheModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("MaHangGhe")
                        .HasColumnType("int");

                    b.Property<int>("TenGhe")
                        .HasColumnType("int");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MaHangGhe");

                    b.ToTable("tb_Ghe");
                });

            modelBuilder.Entity("Cinema.Areas.Admin.Models.HangGheModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("MaPhong")
                        .HasColumnType("int");

                    b.Property<string>("TenHang")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MaPhong");

                    b.ToTable("tb_HangGhe");
                });

            modelBuilder.Entity("Cinema.Areas.Admin.Models.HoaDonModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("MaThanhVien")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayLap")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TongTien")
                        .HasColumnType("decimal(18,3)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MaThanhVien");

                    b.ToTable("tb_HoaDon");
                });

            modelBuilder.Entity("Cinema.Areas.Admin.Models.LoaiPhimModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("TenLoai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("tb_LoaiPhim");
                });

            modelBuilder.Entity("Cinema.Areas.Admin.Models.PhimModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("DaoDien")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DienVien")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("HinhAnh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaLoai")
                        .HasColumnType("int");

                    b.Property<string>("Mota")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("NgayPhatHanh")
                        .HasColumnType("datetime2");

                    b.Property<string>("QuocGia")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TenPhim")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ThoiLuong")
                        .HasColumnType("int");

                    b.Property<string>("Trailer")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MaLoai");

                    b.ToTable("tb_Phim");
                });

            modelBuilder.Entity("Cinema.Areas.Admin.Models.PhongModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("MaRap")
                        .HasColumnType("int");

                    b.Property<int>("TenPhong")
                        .HasMaxLength(50)
                        .HasColumnType("int");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MaRap");

                    b.ToTable("tb_Phong");
                });

            modelBuilder.Entity("Cinema.Areas.Admin.Models.RapPhimModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("HinhAnh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaCumRap")
                        .HasColumnType("int");

                    b.Property<string>("TenRap")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MaCumRap");

                    b.ToTable("tb_RapPhim");
                });

            modelBuilder.Entity("Cinema.Areas.Admin.Models.SuatChieuModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("MaPhim")
                        .HasColumnType("int");

                    b.Property<int>("MaPhong")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayChieu")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ThoiGianBatDau")
                        .HasColumnType("datetime2");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MaPhim");

                    b.HasIndex("MaPhong");

                    b.ToTable("tb_SuatChieu");
                });

            modelBuilder.Entity("Cinema.Areas.Admin.Models.ThanhVienModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GioiTinh")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("HinhAnh")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("SDT")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.Property<string>("TaiKhoan")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("tb_ThanhVien");
                });

            modelBuilder.Entity("Cinema.Areas.Admin.Models.VeModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<decimal>("Gia")
                        .HasColumnType("decimal(18,3)");

                    b.Property<int>("MaGhe")
                        .HasColumnType("int");

                    b.Property<int>("MaHoaDon")
                        .HasColumnType("int");

                    b.Property<int>("MaSuatChieu")
                        .HasColumnType("int");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MaGhe");

                    b.HasIndex("MaHoaDon");

                    b.HasIndex("MaSuatChieu");

                    b.ToTable("tb_Ve");
                });

            modelBuilder.Entity("Cinema.Areas.Admin.Models.GheModel", b =>
                {
                    b.HasOne("Cinema.Areas.Admin.Models.HangGheModel", "Hang")
                        .WithMany("lstGhe")
                        .HasForeignKey("MaHangGhe")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hang");
                });

            modelBuilder.Entity("Cinema.Areas.Admin.Models.HangGheModel", b =>
                {
                    b.HasOne("Cinema.Areas.Admin.Models.PhongModel", "Phong")
                        .WithMany("lstHangGhe")
                        .HasForeignKey("MaPhong")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Phong");
                });

            modelBuilder.Entity("Cinema.Areas.Admin.Models.HoaDonModel", b =>
                {
                    b.HasOne("Cinema.Areas.Admin.Models.ThanhVienModel", "ThanhVien")
                        .WithMany("lstHoaDon")
                        .HasForeignKey("MaThanhVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ThanhVien");
                });

            modelBuilder.Entity("Cinema.Areas.Admin.Models.PhimModel", b =>
                {
                    b.HasOne("Cinema.Areas.Admin.Models.LoaiPhimModel", "Loai")
                        .WithMany("lstPhim")
                        .HasForeignKey("MaLoai")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Loai");
                });

            modelBuilder.Entity("Cinema.Areas.Admin.Models.PhongModel", b =>
                {
                    b.HasOne("Cinema.Areas.Admin.Models.RapPhimModel", "Rap")
                        .WithMany("lstPhong")
                        .HasForeignKey("MaRap")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rap");
                });

            modelBuilder.Entity("Cinema.Areas.Admin.Models.RapPhimModel", b =>
                {
                    b.HasOne("Cinema.Areas.Admin.Models.CumRapModel", "CumRap")
                        .WithMany("lstRapPhim")
                        .HasForeignKey("MaCumRap")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CumRap");
                });

            modelBuilder.Entity("Cinema.Areas.Admin.Models.SuatChieuModel", b =>
                {
                    b.HasOne("Cinema.Areas.Admin.Models.PhimModel", "Phim")
                        .WithMany()
                        .HasForeignKey("MaPhim")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cinema.Areas.Admin.Models.PhongModel", "Phong")
                        .WithMany("lstSuatChieu")
                        .HasForeignKey("MaPhong")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Phim");

                    b.Navigation("Phong");
                });

            modelBuilder.Entity("Cinema.Areas.Admin.Models.VeModel", b =>
                {
                    b.HasOne("Cinema.Areas.Admin.Models.GheModel", "Ghe")
                        .WithMany()
                        .HasForeignKey("MaGhe")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cinema.Areas.Admin.Models.HoaDonModel", "HoaDon")
                        .WithMany("lstVe")
                        .HasForeignKey("MaHoaDon")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cinema.Areas.Admin.Models.SuatChieuModel", "SuatChieu")
                        .WithMany("lstVe")
                        .HasForeignKey("MaSuatChieu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ghe");

                    b.Navigation("HoaDon");

                    b.Navigation("SuatChieu");
                });

            modelBuilder.Entity("Cinema.Areas.Admin.Models.CumRapModel", b =>
                {
                    b.Navigation("lstRapPhim");
                });

            modelBuilder.Entity("Cinema.Areas.Admin.Models.HangGheModel", b =>
                {
                    b.Navigation("lstGhe");
                });

            modelBuilder.Entity("Cinema.Areas.Admin.Models.HoaDonModel", b =>
                {
                    b.Navigation("lstVe");
                });

            modelBuilder.Entity("Cinema.Areas.Admin.Models.LoaiPhimModel", b =>
                {
                    b.Navigation("lstPhim");
                });

            modelBuilder.Entity("Cinema.Areas.Admin.Models.PhongModel", b =>
                {
                    b.Navigation("lstHangGhe");

                    b.Navigation("lstSuatChieu");
                });

            modelBuilder.Entity("Cinema.Areas.Admin.Models.RapPhimModel", b =>
                {
                    b.Navigation("lstPhong");
                });

            modelBuilder.Entity("Cinema.Areas.Admin.Models.SuatChieuModel", b =>
                {
                    b.Navigation("lstVe");
                });

            modelBuilder.Entity("Cinema.Areas.Admin.Models.ThanhVienModel", b =>
                {
                    b.Navigation("lstHoaDon");
                });
#pragma warning restore 612, 618
        }
    }
}
